apiVersion: v1
kind: Service
metadata:
  name: task2-nginx-node-port

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
  selector:
    component: web
    app: task2
