version: '3'

services:
  myredis:
    image: 'redis:alpine'

  mypostgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgresql:/var/lib/postresql/data

  mybackend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    depends_on:
      - 'myredis'
      - 'mypostgres'
    volumes:
      - /opt/myapp/node_modules
      - ./backend/:/opt/myapp

  myfrontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /opt/app/node_modules
      - ./frontend:/opt/app

  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 8080:80
