version: '3'

services:
  my-redis:
    image: 'redis:alpine'
  my-postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./postgresql:/var/lib/postresql/data
  my-backend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    depends_on:
      - 'my-redis'
      - 'my-postgres'
    environment:
      - PORT=${API_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - /opt/myapp/node_modules
      - ./backend/:/opt/myapp
  my-frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /opt/myapp/node_modules
      - ./frontend:/opt/myapp
  my-nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 8080:80
