apiVersion: v1
kind: Service
metadata:
  name: my-ngnix-cluster-ip-service

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-nginx
    component: web
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-ngnix-cluster-ip-service

# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: 80
#   selector:
#     component: server
#     app: my-nginx
