apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nginx-replicaset
  labels:
    app: my-nginx
    component: web

spec:
  template:
    metadata:
      name: my-nginx-pod
      labels:
        app: my-nginx
        component: web
    spec:
      containers:
        - name: my-nginx-container
          image: nginx:alpine
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
      component: web
