apiVersion: v1
kind: Service
metadata:
  name: my-backend-cluster-ip-service

spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: my-backend
    component: backend
