apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-deployment
  labels:
    app: my-backend
    component: backend

spec:
  template:
    metadata:
      name: my-backend-pod
      labels:
        app: my-backend
        component: backend
    spec:
      containers:
        - name: my-backend-container
          image: dkaminski/devops-backend:latest
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: my-backend-configmap
                  key: API_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-configmap
                  key: POSTGRES_DATABASE
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-configmap
                  key: POSTGRES_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-redis-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-redis-configmap
                  key: REDIS_PORT
  replicas: 2
  selector:
    matchLabels:
      app: my-backend
      component: backend
