apiVersion: v1
kind: Service
metadata:
  name: my-backend-node-port-service

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31100
  selector:
    app: my-backend
    component: backend
