apiVersion: v1
kind: Service
metadata:
  name: my-frontend-cluster-ip-service

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-frontend
    component: frontend
