apiVersion: v1
kind: Service
metadata:
  name: my-frontend-node-port-service

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31110
  selector:
    app: my-frontend
    component: frontend
