apiVersion: v1
kind: Service
metadata:
  name: my-redis-cluster-ip-service

spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: my-redis
    component: cache
