apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis-deployment
  labels:
    app: my-redis
    component: cache

spec:
  template:
    metadata:
      name: my-redis-pod
      labels:
        app: my-redis
        component: cache
    spec:
      containers:
        - name: my-redis-container
          image: redis:alpine
          ports:
            - containerPort: 6379
  replicas: 1
  selector:
    matchLabels:
      app: my-redis
      component: cache
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-redis-deployment
#   labels:
#     app: my-redis
#     type: cache

# spec:
#   template:
#     metadata:
#       name: my-redis-pod
#       labels:
#         app: my-redis
#         type: cache
#     spec:
#       containers:
#         - name: my-redis-container
#           image: redis:alpine
#           ports:
#             - containerPort: 6379
#   replicas: 1
#   selector:
#     matchLabels:
#       app: my-redis
#       type: cache
