apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-app-pv
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/docker/dev_ops/my_app_pv
