apiVersion: v1
kind: Pod
metadata:
  name: task1-redis-pod
  labels:
    component: cache
    app: task1

spec:
  containers:
    - name: task1-redis-container
      image: redis:alpine
      ports:
        - containerPort: 6379
